### ISSUE TITLE
ModuleNotFoundError: No module named 'mytest', Different from #115

### ISSUE THREAD

**Issue by Lowell-liu** [linkedin/shiv#144]
shiv --site-packages dist --compressed -p venv/bin/python -o mytest.pyz -e mytest.main:test
mytest
   mytest
      main.py

When executing ./mytest.pyz in debian, result is:

```
Traceback (most recent call last):
  File "./mytest.pyz/_bootstrap/__init__.py", line 68, in import_string
ModuleNotFoundError: No module named 'mytest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./mytest.pyz/_bootstrap/__init__.py", line 68, in import_string
ModuleNotFoundError: No module named 'mytest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "./mytest.pyz/__main__.py", line 3, in <module>
  File "./mytest.pyz/_bootstrap/__init__.py", line 187, in bootstrap
  File "./mytest.pyz/_bootstrap/__init__.py", line 73, in import_string
  File "./mytest.pyz/_bootstrap/__init__.py", line 73, in import_string
  File "./mytest.pyz/_bootstrap/__init__.py", line 51, in import_string
  File "/usr/local/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
```

**Comment by lorencarvalho** [comment]
Hi @Lowell-liu 

Looks to me like `mytest` is probably not included in the `dist/` site-packages directory. If you are making the `pyz` from the root of the package (e.g. in the same dir as `setup.py` or `pyproject.toml`) you can just include `.` in the command line args to indicate to shiv to include the local package. 

Also, I would recommend against using `venv/bin.python` as the argument to `-p`. Whatever you pass to `-p` becomes the shebang of your `pyz`, so in this case it would be `#!venv/bin/python` which is not ideal. Typically the best thing is to pass to `-p` is `/usr/bin/env python3`.
