### ISSUE TITLE
--preamble runpy path error

### ISSUE THREAD

**Issue by Alex-Mann** [linkedin/shiv#163]
I believe this may be an issue on linux machines... but when trying to copy the cleanup example posted in PR #156 exactly, and running with the require flags:
```
... --preamble shiv_cleanup.py ...
```

I get the error:
```
Traceback (most recent call last):
  File "envs/python38/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "envs/python38/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "./mpro/__main__.py", line 3, in <module>
  File "./mpro/_bootstrap/__init__.py", line 219, in bootstrap
  File "envs/python38/lib/python3.8/runpy.py", line 262, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "envs/python38/lib/python3.8/runpy.py", line 232, in _get_code_from_file
    with io.open_code(fname) as f:
TypeError: open_code() argument 'path' must be str, not PosixPath
```

Looks like this is because runpy doesn't support Path objects? Its failing on 232:
```
  230 def _get_code_from_file(run_name, fname):
  231     # Check for a compiled file first
  232     with io.open_code(fname) as f:
  233         code = read_code(f)
  234     if code is None:
  235         # That didn't work, so try it as normal source code
  236         with io.open_code(fname) as f:
  237             code = compile(f.read(), fname, 'exec')
  238     return code, fname
```

As a near term fix, should this pathobj be converted to a string?

**Comment by Alex-Mann** [comment]
So, confirming a fix here... if I update _get_code_from_file in runpy.py:
```
  231 def _get_code_from_file(run_name, fname):
  232     if isinstance(fname, Path): # ADDED CAST
  233         fname = str(fname)
  234     # Check for a compiled file first
  235     with io.open_code(fname) as f:
  236         code = read_code(f)
  237     if code is None:
  238         # That didn't work, so try it as normal source code
  239         with io.open_code(fname) as f:
  240             code = compile(f.read(), fname, 'exec')
  241     return code, fname
```
Adding lines 232+233 above resolves the issue. Since you don't have control of runpy, I guess this fix needs to be added to the bootstrap file.

**Comment by Alex-Mann** [comment]
It looks like this might be an issue in Anaconda which is what I'm running... 

CPython seems to have added support [here](https://github.com/python/cpython/commit/0911ea5c172264eaefa3efe4a1788159c160920d#diff-b54c7484519a659d9f592ddc3c613996).

**Comment by lorencarvalho** [comment]
hey @Alex-Mann,

I've actually observed this too, on Python 3.8.2 on macOS:
```
>       assert proc.returncode == 0
E       AssertionError: assert 1 == 0
E        +  where 1 = CompletedProcess(args=['/private/var/folders/rk/3q7k_qzs7mz4w2j44331qyv40005tq/T/pytest-of-lcarvalh/pytest-40/test_pre..._from_file\n    with io.open_code(fname) as f:\nTypeError: open_code() argument \'path\' must be str, not PosixPath\n').returncode
```

I'd happily ship an RB string-ifying those inputs :)
