### ISSUE TITLE
How to handle packages that compile code

### ISSUE THREAD

**Issue by mhucka** [linkedin/shiv#185]
In an application I'm trying to package with shiv, one of the dependencies is `regex`, and that package seems to need to build a wheel during installation. However, the resulting executable created by shiv doesn't seem to contain some part of it, leading to this error at execution time:
```
Traceback (most recent call last):
  File "./htest/_bootstrap/__init__.py", line 77, in import_string
  File "/Users/mhucka/.shiv/htest_bbc0b1198715e1075b863a66e620b36f3450b713e3660fb6640cc08e6e23b754/site-packages/handprint/__main__.py", line 38, in <module>
    from   commonpy.data_utils import timestamp
  File "/Users/mhucka/.shiv/htest_bbc0b1198715e1075b863a66e620b36f3450b713e3660fb6640cc08e6e23b754/site-packages/commonpy/data_utils.py", line 18, in <module>
    import dateparser
  File "/Users/mhucka/.shiv/htest_bbc0b1198715e1075b863a66e620b36f3450b713e3660fb6640cc08e6e23b754/site-packages/dateparser/__init__.py", line 3, in <module>
    from .date import DateDataParser
  File "/Users/mhucka/.shiv/htest_bbc0b1198715e1075b863a66e620b36f3450b713e3660fb6640cc08e6e23b754/site-packages/dateparser/date.py", line 6, in <module>
    import regex as re
  File "/Users/mhucka/.shiv/htest_bbc0b1198715e1075b863a66e620b36f3450b713e3660fb6640cc08e6e23b754/site-packages/regex/__init__.py", line 1, in <module>
    from .regex import *
  File "/Users/mhucka/.shiv/htest_bbc0b1198715e1075b863a66e620b36f3450b713e3660fb6640cc08e6e23b754/site-packages/regex/regex.py", line 419, in <module>
    import regex._regex_core as _regex_core
  File "/Users/mhucka/.shiv/htest_bbc0b1198715e1075b863a66e620b36f3450b713e3660fb6640cc08e6e23b754/site-packages/regex/_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
```

What is the best way to handle such a Python package?

**Comment by mhucka** [comment]
Never mind. It turns out my problem was due to using one version of Python to build the shiv binary and another version when testing. Using the same version of Python in both cases solved it.
