### ISSUE TITLE
The shiv of release page should probably be generated on Windows

### ISSUE THREAD

**Issue by akgnah** [linkedin/shiv#233]
I downloaded shiv v1.03 from the release page, and when I tried to run it, it didn't work as expected.

``` sh
PS D:\> py -3.9 ./shiv
Traceback (most recent call last):
  File "D:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
.
.
.
  File "C:\Users\Toor\.shiv\shiv_1c0a7a05e4af1a79fd343dde784c153c0929af743f4412922
abd6ce5dbfb620d\site-packages\click\_compat.py", line 541, in auto_wrap_for_ansi
    import colorama
ModuleNotFoundError: No module named 'colorama'
```

According to the traceback message, I found that the [click ](https://github.com/pallets/click/blob/main/pyproject.toml#L17)has additional dependencies on Windows.

It appears that the shiv was generated on Linux, so the builder did not install colorama. 

Then I installed shiv from pip and generated a new shiv, and this time it worked fine.

There may be other users like me who have downloaded it and want to run it to see how it works. 

So I think the shiv of the release page should be generated on Windows.

**Comment by lorencarvalho** [comment]
hey @akgnah 
thanks for the report! I don't have a windows machine handy to make the release, but I could spend the time to automate it via Actions

I'm not sure when I'll find the time, but I will leave this issue open until I do
