### ISSUE TITLE
Crash on Python 3.8 with version 1.0.7: TypeError: 'type' object is not subscriptable

### ISSUE THREAD

**Issue by jakubman1** [linkedin/shiv#258]
As of the latest version in PyPi (1.0.7) I am getting a crash when running shiv on Python 3.8:

```
Traceback (most recent call last):
  File ".../venv/bin/shiv", line 5, in <module>
    from shiv.cli import main
  File ".../venv/lib64/python3.8/site-packages/shiv/cli.py", line 16, in <module>
    from . import builder, pip
  File ".../venv/lib64/python3.8/site-packages/shiv/builder.py", line 21, in <module>
    from . import bootstrap
  File ".../venv/lib64/python3.8/site-packages/shiv/bootstrap/__init__.py", line 16, in <module>
    from .environment import Environment
  File ".../venv/lib64/python3.8/site-packages/shiv/bootstrap/environment.py", line 16, in <module>
    class Environment:
  File ".../venv/lib64/python3.8/site-packages/shiv/bootstrap/environment.py", line 38, in Environment
    hashes: Optional[dict[str, Any]] = None,
TypeError: 'type' object is not subscriptable
```

Seems like the fix would be to use the `typing.Dict` class instead of `dict` for the type hint.

**Comment by jakubman1** [comment]
Seems like the issue is already discussed in https://github.com/linkedin/shiv/pull/255, my bad.
