### ISSUE TITLE
large zipapp in a memory limited docker container fails to bootstrap due to using max workers for compiling site packages

### ISSUE THREAD

**Issue by diefans** [linkedin/shiv#54]
I have a microservice zipapp with a lot of dependencies, which fails to bootstrap in a memory limited docker container:
``` traceback
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/microservice/app.pyz/__main__.py", line 3, in <module>
  File "/microservice/app.pyz/_bootstrap/__init__.py", line 106, in bootstrap
  File "/microservice/app.pyz/_bootstrap/__init__.py", line 80, in extract_site_packages
  File "/usr/local/lib/python3.6/compileall.py", line 86, in compile_dir
    success = min(results, default=True)
  File "/usr/local/lib/python3.6/concurrent/futures/process.py", line 366, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 586, in result_iterator
    yield fs.pop().result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/usr/local/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
```
I am wondering/asking if it would be possible to limit the number of workers used to compile the site packages in https://github.com/linkedin/shiv/blob/master/src/shiv/bootstrap/__init__.py#L80 by specifying it at zipapp creation time or even completely disable pre-compilation (I guess, at least in my case a lot of modules from some dependencies are not used anyway)?

compiling with max workers(*):
![mprof-zipapp-memory](https://user-images.githubusercontent.com/513316/44577990-bf384580-a792-11e8-9b3c-46fb4a10f266.png)

no pre-compiling:
![mprof-zipapp-memory-no-compile](https://user-images.githubusercontent.com/513316/44578008-c8c1ad80-a792-11e8-8760-e13695d3d984.png)

In my case (zipapp in docker to save image size) compilation does not work well, it takes a lot of memory and extends the bootstrap phase unnecessary.

\* - profiling done with https://pypi.org/project/memory_profiler/

**Comment by sixninetynine** [comment]
@diefans released on pypi 0.0.31
