### ISSUE TITLE
Printing the "knife" emoji crashes when the codepage doesn't support it

### ISSUE THREAD

**Issue by pfmoore** [linkedin/shiv#82]
On Windows, the console supports UTF8, and since Python 3.6 console output does too. But output to a pipe or file (and presumably any other case where the output doesn't support full Unicode, such as a Unix system with an encoding other than UTF-8 specified) crashes:

```
>shiv shiv >a.txt
Traceback (most recent call last):
  File "C:\[...]\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\[...]\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Utils\Misc\shiv.pyz\__main__.py", line 3, in <module>
  File "C:\Utils\Misc\shiv.pyz\_bootstrap\__init__.py", line 137, in bootstrap
  File "C:\[...]\.shiv\shiv_fbaa7543-371f-4f00-99fc-7a416dfdc32a\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "C:\[...]\.shiv\shiv_fbaa7543-371f-4f00-99fc-7a416dfdc32a\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "C:\[...]\.shiv\shiv_fbaa7543-371f-4f00-99fc-7a416dfdc32a\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\[...]\.shiv\shiv_fbaa7543-371f-4f00-99fc-7a416dfdc32a\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "C:\[...]\.shiv\shiv_fbaa7543-371f-4f00-99fc-7a416dfdc32a\site-packages\shiv\cli.py", line 150, in main
    click.secho(" shiv! " + SHIV, bold=True)
  File "C:\[...]\.shiv\shiv_fbaa7543-371f-4f00-99fc-7a416dfdc32a\site-packages\click\termui.py", line 420, in secho
    return echo(style(text, **styles), file=file, nl=nl, err=err, color=color)
  File "C:\[...]\.shiv\shiv_fbaa7543-371f-4f00-99fc-7a416dfdc32a\site-packages\click\utils.py", line 259, in echo
    file.write(message)
  File "C:\[...]\Python37\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\U0001f52a' in position 7: character maps to <undefined>
```

Something like the following fix to cli.py should address the issue:

```python
# This is the 'knife' emoji
SHIV = u"\U0001F52A"
try:
    SHIV.encode(sys.stdout.encoding)
except UnicodeEncodeError:
    SHIV = "!"
```

**Comment by sixninetynine** [comment]
tbqh I've always been annoyed at myself for including the emoji and the begin/end output. just cut a PR to remove them entirely

I've thought about even suppressing pip's output (via `-q`) by default in favor of a `-v` to opt _into_ verbosity, perhaps in a later change...
